import { Inter } from 'next/font/google'
import './globals.css'
import Footer from './footer/page'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <script src="http://dapi.kakao.com/v2/maps/sdk.js?appkey=6af72bb162b060fec44d4603ee93c1c0"></script>
      </head>
      {/* <body className={inter.className}> */}
      <body>
        {children}
        <Footer />
      </body>
    </html>
  )
}
